// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sensormine.Core.Models;
using Sensormine.Storage.Data;

#nullable disable

namespace Sensormine.Storage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207121339_SyncModelChanges")]
    partial class SyncModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sensormine.Core.Models.AlertDeliveryChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, object>>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseDefaultTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("use_default_template");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_alert_delivery_channels_enabled");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alert_delivery_channels_tenant");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_alert_delivery_channels_type");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_alert_delivery_channels_tenant_name");

                    b.ToTable("alert_delivery_channels", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.AlertInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AcknowledgmentNotes")
                        .HasColumnType("text")
                        .HasColumnName("acknowledgment_notes");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<Dictionary<string, object>>("FieldValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_values");

                    b.Property<bool>("IsEscalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_escalated");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("NotificationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("notification_count");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("ix_alert_instances_rule");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_alert_instances_device");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_alert_instances_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_alert_instances_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alert_instances_tenant");

                    b.HasIndex("TriggeredAt")
                        .IsDescending()
                        .HasDatabaseName("ix_alert_instances_triggered_at");

                    b.ToTable("alert_instances", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionLogic")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("condition_logic");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("DeliveryChannels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("delivery_channels");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<Guid>>("DeviceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("device_ids");

                    b.PrimitiveCollection<List<Guid>>("DeviceTypeIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("device_type_ids");

                    b.Property<string>("EscalationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("escalation_rule");

                    b.Property<int>("EvaluationFrequencySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_frequency_seconds");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Recipients")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recipients");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TimeWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_window_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_alert_rules_enabled");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_alert_rules_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TargetType")
                        .HasDatabaseName("ix_alert_rules_target_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alert_rules_tenant");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_alert_rules_tenant_name");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.Dashboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DashboardType")
                        .HasColumnType("integer")
                        .HasColumnName("dashboard_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentDashboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_dashboard_id");

                    b.Property<string>("SharedWith")
                        .HasColumnType("jsonb")
                        .HasColumnName("shared_with");

                    b.Property<string>("Tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("template_category");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("Widgets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("widgets");

                    b.HasKey("Id");

                    b.HasIndex("IsTemplate")
                        .HasDatabaseName("ix_dashboards_is_template");

                    b.HasIndex("ParentDashboardId")
                        .HasDatabaseName("ix_dashboards_parent");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_dashboards_tenant");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_dashboards_user");

                    b.HasIndex("TenantId", "ParentDashboardId")
                        .HasDatabaseName("ix_dashboards_tenant_parent");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_dashboards_tenant_user");

                    b.ToTable("dashboards", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Dictionary<string, object>>("CustomFieldValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_field_values");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Location>("Location")
                        .HasColumnType("jsonb")
                        .HasColumnName("location");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_id");

                    b.HasIndex("DeviceTypeId")
                        .HasDatabaseName("ix_devices_device_type_id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_devices_last_seen_at");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_devices_serial_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_devices_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_devices_tenant_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertTemplates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alert_templates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocol");

                    b.Property<string>("ProtocolConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("protocol_config");

                    b.Property<Guid?>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_device_types_active");

                    b.HasIndex("Protocol")
                        .HasDatabaseName("ix_device_types_protocol");

                    b.HasIndex("Tags")
                        .HasDatabaseName("ix_device_types_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_device_types_tenant");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_device_types_tenant_name")
                        .HasFilter("is_active = true");

                    b.ToTable("device_types", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.DeviceTypeAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_device_type_audit_logs_action");

                    b.HasIndex("DeviceTypeId")
                        .HasDatabaseName("ix_device_type_audit_logs_device_type");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_device_type_audit_logs_tenant");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_device_type_audit_logs_timestamp");

                    b.ToTable("device_type_audit_logs", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.DeviceTypeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("VersionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("version_data");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId")
                        .HasDatabaseName("ix_device_type_versions_device_type");

                    b.HasIndex("DeviceTypeId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_device_type_versions_device_type_version");

                    b.ToTable("device_type_versions", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.Schema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_schemas_deleted");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schemas_tenant");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_schemas_tenant_name")
                        .HasFilter("is_deleted = false");

                    b.ToTable("schemas", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.SchemaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("DeviceTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("device_types");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_schema");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_schema_versions_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schema_versions_tenant");

                    b.HasIndex("SchemaId", "IsDefault")
                        .HasDatabaseName("ix_schema_versions_schema_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("SchemaId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_schema_versions_schema_version");

                    b.ToTable("schema_versions", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.SiteConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Defaults")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("defaults");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<string>("Integrations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("integrations");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("SiteSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("site_settings");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("ix_site_configurations_tenant_key");

                    b.ToTable("site_configurations", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DashboardPreferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dashboard_preferences");

                    b.Property<string>("DataPreferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_preferences");

                    b.Property<string>("DisplayPreferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("display_preferences");

                    b.Property<string>("Favorites")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("favorites");

                    b.Property<string>("NotificationPreferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notification_preferences");

                    b.Property<string>("RecentlyViewed")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recently_viewed");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_preferences_user");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_tenant_user");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Sensormine.Core.Models.AlertInstance", b =>
                {
                    b.HasOne("Sensormine.Core.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sensormine.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Sensormine.Core.Models.Dashboard", b =>
                {
                    b.HasOne("Sensormine.Core.Models.Dashboard", "ParentDashboard")
                        .WithMany("SubPages")
                        .HasForeignKey("ParentDashboardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentDashboard");
                });

            modelBuilder.Entity("Sensormine.Core.Models.Device", b =>
                {
                    b.HasOne("Sensormine.Core.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("Sensormine.Core.Models.DeviceTypeAuditLog", b =>
                {
                    b.HasOne("Sensormine.Core.Models.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensormine.Core.Models.DeviceTypeVersion", b =>
                {
                    b.HasOne("Sensormine.Core.Models.DeviceType", null)
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensormine.Core.Models.SchemaVersion", b =>
                {
                    b.HasOne("Sensormine.Core.Models.Schema", "Schema")
                        .WithMany("Versions")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Sensormine.Core.Models.Dashboard", b =>
                {
                    b.Navigation("SubPages");
                });

            modelBuilder.Entity("Sensormine.Core.Models.Schema", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
