// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusConfiguration.API.Data;
using NexusConfiguration.API.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusConfiguration.API.Data.Migrations
{
    [DbContext(typeof(NexusConfigurationDbContext))]
    partial class NexusConfigurationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusConfiguration.API.Models.NexusConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiInsights")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("ai_insights");

                    b.Property<List<AlertRuleTemplate>>("AlertRuleTemplates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alert_rule_templates");

                    b.Property<CommunicationSettings>("CommunicationSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("communication_settings");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomLogic")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("custom_logic");

                    b.Property<string>("CustomLogicLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("custom_logic_language");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DeviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_type_id");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<List<ProbeConfig>>("ProbeConfigurations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("probe_configurations");

                    b.Property<Dictionary<string, string>>("SchemaFieldMappings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_field_mappings");

                    b.Property<Guid?>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.Property<DocumentInfo>("SourceDocument")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_document");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("TemplateCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_category");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("IsTemplate")
                        .HasDatabaseName("ix_nexus_configurations_is_template");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_nexus_configurations_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_nexus_configurations_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_nexus_configurations_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_nexus_configurations_tenant_name");

                    b.ToTable("nexus_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
